generic-service:
  nameOverride: hmpps-cell-sharing-risk-assessment-api
  productId: "DPS126" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  serviceAccountName: hmpps-cell-sharing-risk-assessment-api

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-cell-sharing-risk-assessment-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: cell-sharing-risk-assessment-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-cell-sharing-risk-assessment-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-postgresql-instance-output:
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"

  allowlist:
    groups:
      - internal

  modsecurity_enabled: true
  modsecurity_snippet: |
    SecRuleEngine DetectionOnly
    SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"        

generic-prometheus-alerts:
  targetApplication: hmpps-cell-sharing-risk-assessment-api
