---
# Per environment values which override defaults in hmpps-cell-sharing-risk-assessment-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: cell-sharing-risk-assessment-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-secret:
      HMPPS_SQS_QUEUES_CSRA_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-dlq-secret:
      HMPPS_SQS_QUEUES_CSRA_DLQ_NAME: "sqs_queue_name"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-nonprod
